### PR TITLE
Update AudioKit Swiftpackage

### PR DESCRIPTION
**Pull request by emurray2**
I updated things to the latest AudioKit Swift Package.

### CODE REVIEW

**Comment by urbansmash** [comment]
🔥🙌🏾😎💫

**Comment by emurray2** [comment]
More PR's on the way! Let me know if everything so far is working alright. I'm planning on connecting the buttons to play the samples tomorrow.

**Comment by urbansmash** [comment]
😎🙌🏾 I’ll try my Xcode on Monday.  My iPhone and iPad support the latest iOS 14.6.  However, my MacBook stops at Catalina.  It no longer supports later macOS (such as Big Sur).  This means my Xcode versions will also be limited.  

Hope to get a developer account sorted so we can side load (deploy) wirelessly/remotely onto multiple iOS devices.  

Bless, 
UrbanSmash

**Comment by emurray2** [comment]
> 😎🙌🏾 I’ll try my Xcode on Monday.  My iPhone and iPad support the latest iOS 14.6.  However, my MacBook stops at Catalina.  It no longer supports later macOS (such as Big Sur).  This means my Xcode versions will also be limited.  
> 
> Hope to get a developer account sorted so we can side load (deploy) wirelessly/remotely onto multiple iOS devices.  
> 
> Bless, 
> UrbanSmash 
> 
> > On 19 Jun 2021, at 21:25, Evan Murray ***@***.***> wrote:
> > 
> > ﻿
> > More PR's on the way! Let me know if everything so far is working alright. I'm planning on connecting the buttons to play the samples tomorrow.
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Ahh I see. Sounds good! Well, we're in luck! I just got a developer account a couple days ago, so we can use mine :) !

**Comment by urbansmash** [comment]
Perfect 💯🙌🏾😎

**Pull request merged**
